version: "3"

services:

    mongodb:
        image: mongo:3.2

    webhook:
        build: .
        command: bash -c "echo 'nothing todo'"
        ports:
            - 8000:8000
        depends_on:
            - mongodb
        volumes:
            - .:/code
